name: Helm Validation

on:
  push:
    branches:
      - main

env:

  CHART_PATH: ./helm/rajesh-web



jobs:

  helm-validation:

    runs-on: ubuntu-latest

    strategy:

      matrix:

        environment:

          - dev

          - qa

          - prod
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Helm Version
        run: helm version

      - name: Helm Lint
        run: helm lint $CHART_PATH

      - name: Helm Template

        run: |
          helm template \
            rajesh-${{ matrix.environment }} \
            $CHART_PATH \
            -f ./environments/${{ matrix.environment }}/rajesh-web-values.yaml